#!/usr/bin/env ansible-playbook

- name: Deploy
  hosts: all
  gather_facts: false
  vars:
    env: prod
    prefix: /var/www/ch2rss-{{ env }}
  tasks:
    - name: remove existing virtualenv
      file: path="{{ prefix }}/.venv" state=absent
      tags: full

    - name: upload {{ playbook_dir }} to {{ prefix }}
      synchronize: src={{ playbook_dir }}/ dest={{ prefix }} archive=no recursive=yes perms=yes

    - name: create cache and tools directories
      file: path={{ item }} state=directory owner=www-data
      loop:
        - /var/www/.local
        - /var/www/.cache
        - /var/www/.config
        - /var/www/.ansible
        - "{{ prefix }}/.venv"
      tags: full

    - name: cleanup UV cache
      command: uv cache clean
      args:
        chdir: "{{ prefix }}"
      become: true
      become_user: www-data
      tags: full

    - name: create virtualenv
      shell: uv venv -q
      args:
        chdir: "{{ prefix }}"
      become: true
      become_user: www-data
      tags: full

    - name: install dependencies
      shell: uv sync --frozen || uv sync --frozen --refresh
      args:
        chdir: "{{ prefix }}"
      become: true
      become_user: www-data

    - name: install supervisor config
      file: state=link src={{ prefix }}/supervisor.conf dest=/etc/supervisor/conf.d/ch2rss.conf
      tags: full

    - name: set stats.json permissions
      file: path={{ prefix }}/public/stats.json state=touch owner=www-data group=www-data mode=0644
      tags: full

    - name: check if crontab file exists locally
      local_action: stat path=crontab
      register: crontab_file

    - name: install crontab
      copy: src=crontab dest=/etc/cron.d/ch2rss owner=root
      when: crontab_file.stat.exists
      tags: full

    - name: restart process
      supervisorctl: name=ch2rss state=restarted
